import sql from "./db"

let migrated = false
export async function migrate() {

    if (migrated) return
    migrated = true

    console.log("checking/creating a new notes table")

    await sql`
        create table if not exists notes (
            id bigint generated by default as identity primary key,
            created_at timestamp with time zone not null default now(),
            modified_at timestamp with time zone null default now(),
            markdown text null,
            public_uuid UUID default gen_random_uuid() unique,
            public_url boolean default false,
            public_pane boolean default false,
            pinned boolean default false
        )
    `
}

export async function getNotes() {
    await migrate()

    const notes = await sql`
        select * from notes order by created_at desc
    `

    return notes
}

export async function getNoteByID(id) {
    await migrate()

    const [note] = await sql`
        select *
        from 
            notes
        where
            id = ${id}
    `

    return note || null
}

export async function getNoteByUUID(uuid) {
    await migrate()

    const [note] = await sql`
        select *
        from 
            notes
        where
            public_uuid = ${uuid}
    `

    return note || null
}

export async function addNote(markdown, public_url, public_pane, created_at, modified_at) {
    await migrate()

    //todo something better
    //i hate myself
    if (created_at !== undefined && modified_at !== undefined) {
        return await sql`
            insert into notes 
                (markdown, public_url, public_pane, created_at, modified_at)
            values
                (${markdown}, ${public_url}, ${public_pane}, ${created_at}, ${modified_at})
            returning *
        `
    } else if (created_at !== undefined) {
        return await sql`
            insert into notes 
                (markdown, public_url, public_pane, created_at)
            values
                (${markdown}, ${public_url}, ${public_pane}, ${created_at})
            returning *
        `
    } else if (modified_at !== undefined) {
        return await sql`
            insert into notes 
                (markdown, public_url, public_pane, modified_at)
            values
                (${markdown}, ${public_url}, ${public_pane}, ${modified_at})
            returning *
        `
    } else {
        return await sql`
            insert into notes 
                (markdown, public_url, public_pane)
            values
                (${markdown}, ${public_url}, ${public_pane})
            returning *
        `
    }
}

export async function modifyNote(id, markdown, public_url, public_pane, pinned) {
    await migrate()


    //replace any missing data with old data
    const oldData = await getNoteByID(id)

    if (markdown === undefined) {
        markdown = oldData.markdown
    }

    if (public_url === undefined) {
        public_url = oldData.public_url
    }
    
    if (public_pane === undefined) {
        public_pane = oldData.public_pane
    }

    if (pinned === undefined) {
        pinned = oldData.pinned
    }

    const [note] = await sql`
        update notes
        set 
            modified_at = now(),
            markdown = ${markdown},
            public_url = ${public_url},
            public_pane = ${public_pane},
            pinned = ${pinned}
        where id = ${id}
        returning *
    `

    return note
}

export async function removeNote(id) {
    await migrate()

    const [note] = await sql`
        delete from notes
        where
            id = ${id}
        returning *
    `

    return note
}

// delete unneccesary information
export function sanitizeNote(sensitive) {

    let note = {
        created_at: sensitive.created_at,
        modified_at: sensitive.modified_at,
        markdown: sensitive.markdown,
        public_url: sensitive.public_url,
        public_pane: sensitive.public_pane,
        public_uuid: sensitive.public_uuid
    }

    if (!note.public_url) {
        delete note.public_uuid
        delete note.public_url
    }

    if (!note.public_pane) {
        delete note.public_pane
    }

    return note
}